source 'http://rubygems.org'

gem 'rails', '~> 3.1.1'
gem 'haml-rails'

gem 'sqlite3'

gem 'interpret', :path => ".."
gem 'mysql2', "~> 0.3.0"

gem 'jquery-rails'

group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end
