source 'http://rubygems.org'

gem 'rails', '~> 3.0.5'
gem 'haml-rails'
gem 'capistrano'

group :development, :test do
  gem 'sqlite3-ruby', :require => 'sqlite3'
end

gem 'interpret', :path => ".."
gem 'mysql2', "~> 0.2.7"
