source 'http://rubygems.org'

gem 'rails', '~> 3.0.5'
gem 'haml-rails'
gem 'capistrano'

group :development, :test do
  gem 'sqlite3-ruby', :require => 'sqlite3'
  gem 'ruby-debug'
end

gem 'interpret', :path => ".."
